#!/bin/bash

sudo mkdir -p /run/media/Media
sudo mkdir -p /run/media/Learn


echo "# My media drives
UUID=01D61E46881C0510                     /run/media/Learn     ntfs    defaults  0  0
UUID=01D61E46980A6390                     /run/media/Media     ntfs    defaults  0  0" >> /etc/fstab