#!/bin/bash

if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
    ...
elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
    ...
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
fi

current_distro=$(echo "$OS" | tr '[:upper:]' '[:lower:]')


currentPackageManager=''
case $current_distro in
    fedora) currentPackageManager="dnf";;
    "arch linux") currentPackageManager="pacman";;
    ubuntu) currentPackageManager="apt";;
    "manjaro linux") currentPackageManager="pacman";;
    "garuda linux") currentPackageManager="pacman";;
    *) echo "Cannot find package manager for you distro. Check get_package_manager file." && exit;;
esac

echo $currentPackageManager
