#!/bin/bash

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "....................  Installing ZSH  .........................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;

cd ~/.cache
git clone https://github.com/sidmoreoss/ezsh.git
cd ezsh
./install.sh -c        # only run with '-c' the first time, running multiple times will duplicate history entries


