#!/bin/bash

currentPackageManager="$1"
currentDE="$2"

if [[ $1 == '-h' || $1 == '--help' ]]
then
    echo "Usage: install_favorites DESKTOPENV(kde, qtile) DISTRO(fedora, arch)" && exit;
fi

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "............  Installing Favorite Applications  ...............";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;


sudo true;

packageListqtile=(
    ## notification daemon, rofi and alacritty
    dunst
    rofi
    alacritty
    
    ## misc tools
    flameshot
    fzf
    ripgrep
    
    
    ## Browsers
    brave
    firefox
    qbittorrent
    
    ## File managers
    thunar
    thunar-volman
    thunar-archive-plugin
    thunar-media-tags-plugin
    thunar-shares-plugin
    gtkhash-thunar
    
    ## Media tools
    audacious
    smplayer
    shotwell
    epdfview
    easytag
    playerctl
    ffmpegthumbs
    
    ## Code Editors, Text Editors
    neovim
    geany
    marker
    
    ## Fonts
    ttf-font-awesome
    ttf-jetbrains-mono
    ttf-inconsolata
    ttf-dejavu
    
    ## Wallpaper Changers
    variety
    python-pywal
    
    ## System utilities
    arandr
    lxappearance
    file-roller
    polkit-gnome
    python-psutil
    xfce4-power-manager
    xfce4-settings
    xfconf
    qt5ct
    kvantum-qt5
    xcb-util-cursor
    zsh
    python3-pip
    python-pip
    axel
    ttf-mononoki-git
)

packageListkde=(
    # applications
    flameshot
    fzf
    zsh
    git
    wget
    curl
    sddm
    qbittorrent
    smplayer
    playerctl
    neovim
    alacritty
    variety
    python-pywal
    krename
    ffmpegthumbs
    python3-pip
    python-pip
    axel
    latte-dock-git
    kvantum-qt5
    libinput_gestures_qt

    # fonts
    ttf-font-awesome
    ttf-jetbrains-mono
    ttf-inconsolata
    ttf-dejavu
    freetype2
    ttf-mononoki-git
    ttf-windows
    ttf-merriweather-sans

    # extensions
#     plasma5-applets-virtual-desktop-bar-git
#     plasma5-applets-window-title
#     plasma5-applets-window-appmenu-git
#     plasma5-applets-window-buttons-git
#     plasma5-applets-eventcalendar
#     plasma5-wallpapers-dynamic
#     kwin-bismuth
    packagekit-qt5
    kcharselect
)

install_package() {
    sudo $currentPMSyntax $1
}

installPackages(){
    count=0
    x=$currentDE
    req_list=packageList$x[@]
    for name in "${!req_list}" ; do
        count=$[count+1]
        tput setaf 3;echo "Installing package #.  "$count " " $name;tput sgr0;
        install_package $name
    done
}

installYayPackages(){
    count=0
    x=$currentDE
    req_list=packageList$x[@]
    for name in "${!req_list}" ; do
        count=$[count+1]
        tput setaf 3;echo "Installing package #.  "$count " " $name;tput sgr0;
        yay -S --noconfirm --needed $name
    done
}

install_yay(){
    if ! type "yay" >> /dev/null 2>&1; then
        echo "Installing Yay"
        sudo pacman -Syyu --noconfirm
        sudo pacman -S git --noconfirm --needed
        mkdir -p ~/Downloads
        cd ~/Downloads || exit
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
    fi
}

case $currentPackageManager in
    "dnf")
        sudo dnf update -y
        currentPMSyntax="dnf install -y"
        installPackages
    ;;
    
    "pacman")
        install_yay || (echo "Yay cannot be installed, aborting" && exit);
        currentPMSyntax="pacman --needed --noconfirm -S "
        installYayPackages
    ;;
    
    "apt")
        sudo apt update -y
        currentPMSyntax="apt install -y"
        installPackages
    ;;
    
    *)
    echo "Wrong package manager. Please check install_favorites" && exit;;
    
    
esac

# Install pywal (wallpaper)
sudo pip3 install pywal

## Uncomment below if you recently installed sddm
# sudo systemctl enable sddm.service --force

echo
tput setaf 2;echo "Installation Successfull";tput sgr0;
tput setaf 5;echo "Please chech the install before rebooting";tput sgr0;


# tput setaf 2;echo "Instaling Other Apps...";tput sgr0;

# # ./install_google_chrome $1
# # ./install_visual_studio_code $1
# # ./install_brave $1




