#!/bin/bash

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "....................  Installing ZSH  .........................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;

cd ../../ZSH/ || exit
cp -bl .aliases ~/ || exit

cd ~/Downloads
git clone https://github.com/sidmoreoss/quickz-sh
cd quickz-sh
./quickz.sh -c        # only run with '-c' the first time, running multiple times will duplicate history entries


