#!/bin/bash


tput setaf 5;echo "Do you want to install Visual Studio Code? [y/n]";tput sgr0;
read -t 30 -r input
case $input in
    y*) ;;
    *) exit ;;

esac


install_for_apt(){
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
    sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    sudo apt install apt-transport-https -y
    sudo apt update -y
    sudo apt install code -y
}

install_for_dnf(){
    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    sudo dnf check-update -y
    sudo dnf install code -y
}

install_for_pacman(){
    yay -S --noconfirm visual-studio-code-bin
}

current_package_manager="$1"

"install_for_""$current_package_manager"