#!/bin/bash

currentPackageManager="$1"
currentDE="$2"

if [[ $1 == '-h' || $1 == '--help' ]]
then
    echo "Usage: install_favorites DESKTOPENV(kde, qtile) DISTRO(fedora, arch)" && exit;
fi

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "............  Installing Favorite Applications  ...............";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;


sudo true;

packageListqtile=(
    ## notification daemon, rofi and alacritty
    dunst
    rofi
    alacritty
    
    ## misc tools
    flameshot
    fzf
    ripgrep
    
    
    ## Browsers
    brave
    firefox
    qbittorrent
    
    ## File managers
    thunar
    thunar-volman
    thunar-archive-plugin
    thunar-media-tags-plugin
    thunar-shares-plugin
    gtkhash-thunar
    
    ## Media tools
    audacious
    smplayer
    shotwell
    epdfview
    easytag
    playerctl
    ffmpegthumbs
    
    ## Code Editors, Text Editors
    neovim
    geany
    marker
    
    ## Fonts
    ttf-font-awesome
    ttf-jetbrains-mono
    ttf-inconsolata
    ttf-dejavu
    
    ## Wallpaper Changers
    variety
    python-pywal
    
    ## System utilities
    arandr
    lxappearance
    file-roller
    polkit-gnome
    python-psutil
    xfce4-power-manager
    xfce4-settings
    xfconf
    qt5ct
    kvantum-qt5
    xcb-util-cursor
    zsh
    python3-pip
    python-pip
    axel
    ttf-mononoki-git
)

packageListkde=(
    flameshot
    fzf
    ripgrep
    zsh
    git
    wget
    curl
    
    brave
    firefox
    qbittorrent
    
    audacious
    smplayer
    playerctl
    
    neovim
    
    ttf-font-awesome
    ttf-jetbrains-mono
    ttf-inconsolata
    ttf-dejavu
    
    variety
    python-pywal
    krename
    ffmpegthumbs
    python3-pip
    python-pip
    
    axel
    latte-dock-git
    plasma5-applets-virtual-desktop-bar-git
    plasma5-applets-window-title
    plasma5-applets-window-appmenu-git
    plasma5-applets-window-buttons-git
    kvantum-qt5
)

yay_install() {
    yay -S --noconfirm --needed $1
}

install_package() {
    sudo $currentPMSyntax $1
}

installPackages(){
    count=0
    x=$currentDE
    req_list=packageList$x[@]
    for name in "${!req_list}" ; do
        count=$[count+1]
        tput setaf 3;echo "Installing package #.  "$count " " $name;tput sgr0;
        install_package $name
    done
}

installYayPackages(){
    count=0
    x=$currentDE
    req_list=packageList$x[@]
    for name in "${!req_list}" ; do
        count=$[count+1]
        tput setaf 3;echo "Installing package #.  "$count " " $name;tput sgr0;
        install_package $name
    done
}

install_yay(){
    if ! type "yay" >> /dev/null 2>&1; then
        echo "Installing Yay"
        sudo pacman -Syyu --noconfirm
        sudo pacman -S git --noconfirm
        mkdir -p ~/Downloads
        cd ~/Downloads || exit
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
    fi
}



### Arch specific stuff ###
ua-drop-caches(){
    sudo paccache -rk3;
    yay -Sc --aur --noconfirm
}
ua-update-all(){
    export TMPFILE="$(mktemp)";
    sudo true;
    rate-arch-mirrors --max-delay=21600 | tee -a $TMPFILE || exit \
    && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-backup \
    && sudo mv $TMPFILE /etc/pacman.d/mirrorlist \
    && ua-drop-caches \
    && yay -Syyu --noconfirm
}
### end ###


case $currentPackageManager in
    "dnf")
        sudo dnf update -y
        currentPMSyntax="dnf install -y"
        installPackages
    ;;
    
    "pacman")
        install_yay || (echo "Yay cannot be installed, hence aborting" && exit);
        yay --needed --noconfirm -S rate-arch-mirrors || (echo "Rate arch mirrors cannot be installed, aborting" && exit);
        ua-drop-caches
        ua-update-all
        currentPMSyntax="pacman --needed --noconfirm -S "
        installYayPackages
    ;;
    
    "apt")
        sudo apt update -y
        currentPMSyntax="apt install -y"
        installPackages
    ;;
    
    *)
    echo "Wrong package manager. Please check install_favorites" && exit;;
    
    
esac

# Install pywal (wallpaper)
sudo pip3 install pywal

echo
tput setaf 2;echo "Installation Successfull!";tput sgr0;
tput setaf 5;echo "Reboot now!!!";tput sgr0;


# tput setaf 2;echo "Instaling Other Apps...";tput sgr0;

# # ./install_google_chrome $1
# # ./install_visual_studio_code $1
# # ./install_brave $1




