#!/bin/bash

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "....................  Installing ZSH  .........................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;


sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting


cd ../../ZSH/ || exit

## Uncomment to install bash
# shopt -s dotglob nullglob
# cp -rv bash* ~/

# Install ZSH by default
cp -bl .zshrc ~/ || exit
cp -bl .aliases ~/ || exit
