#!/bin/bash

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "....................  Installing ZSH  .........................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;



cd ../../ZSH/ || exit

## Uncomment to install bash
# shopt -s dotglob nullglob
# cp -rv bash* ~/

# Install ZSH by default
cp -ruvb .zshrc ~/ || exit
cp -ruvb .aliases ~/ || exit

cd ../.config/ || exit
cp -r oh-my-zsh ~/.config/ || exit


chsh -s "$(which zsh)"


# Breaking because ohmyzsh is a sub repo