#!/bin/bash

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
source ~/.zshrc

git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/plugins/zsh-syntax-highlighting

if grep -Fxq "#Custom settings by sidmoreoss@gmail.com" ~/.zshrc
then
    echo "Config already installed" && exit;
else
    echo "#Custom settings by sidmoreoss@gmail.com" >> ~/.zshrc
    echo "plugins+=(zsh-autosuggestions zsh-syntax-highlighting)" >> ~/.zshrc
fi

source ~/.zshrc
