#!/bin/bash


echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo ".............  Making all scripts executable  .................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;

chmod +x utils/* || echo "cannot modify"

chmod +x ./*

mkdir -vp ~/.local/bin/

mkdir -vp ~/.config/

mkdir -vp ~/.cache/

# Tested works fine