#!/bin/bash

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo ".................  Setting global path  .......................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;


cat > /etc/profile.d/myPathForBinaries.sh << \EOF
PATH=$PATH:~/.local/bin
EOF

# Tested works fine