#!/bin/bash

sudo dnf install fedora-workstation-repositories

sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

# Install Python pip3 if not already installed
sudo dnf install python3-pip -y

../setAvatar
../install_kde