#!/bin/bash

git clone https://github.com/ishovkun/taglist
cd taglist || return

echo "Installing taglist"
kpackagetool5 -t Plasma/Applet --install package

echo
echo "Success"

echo
echo "Cleaning workspace"
cd ..
rm -r taglist

echo
echo "Successfully installed taglist, now apply the widget using \'Add Widget\' option"

echo
echo "For more details visit: https://github.com/ishovkun/taglist"