#!/bin/bash

#########################################################################################

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "..................  Setting your avatar .......................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;

# Create avatar png files and required symlink
cp ../.face.png ~/ -v
ln -s ~/.face.png ~/.face.icon

# Set permissions for sddm
setfacl -m u:sddm:x ~/
setfacl -m u:sddm:r ~/.face.icon

#########################################################################################

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo "..................  Installing KDE Desktop  ...................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;


cd ../../common || exit;

## Install apps and binaries
chmod +x make_executables
./make_executables || exit;
./install_binaries || exit;
./install_favorites "$1" kde || exit;
./install_zsh || exit;

## Install configuration
cd ../../.config/ || exit;
echo "Moving configurations"
cp -rv alacritty ~/.config/  || exit;

# Install Pywal (Wallpaper accent colors chooser)
# TODO: Verify that set-pywal is correctly installed
set-pywal kde -n

# tput setaf 5;echo "Do you want to install pywal (wallpaper accent colors) for firefox??";tput sgr0;
# read -r input
# case $input in
#     y*) ./pywal_firefox  || exit;
# esac

#########################################################################################

echo "Reboot to take effect"
