#!/bin/bash

echo
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
tput setaf 2;echo ".........................  PYWAL KDE  .........................";tput sgr0;
tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;


hex2rgb() {
    hex=$(echo "${1^^}" | sed 's/#//g')

    a=$(echo $hex | cut -c-2)
    b=$(echo $hex | cut -c3-4)
    c=$(echo $hex | cut -c5-6)

    r=$(echo "ibase=16; $a" | bc)
    g=$(echo "ibase=16; $b" | bc)
    b=$(echo "ibase=16; $c" | bc)

    echo $r,$g,$b
}

source ~/.cache/wal/colors.sh

 
 
color0=$(hex2rgb $color2)
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Button" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Button" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Button" --key "ForegroundActive" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Complementary" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Complementary" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Complementary" --key "ForegroundActive" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Header" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Header" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Header" --key "ForegroundActive" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Header" --group "Inactive" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Header" --group "Inactive" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Header" --group "Inactive" --key "ForegroundActive" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Selection" --key "BackgroundNormal" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Selection" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Selection" --key "DecorationFocus" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Tooltip" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Tooltip" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Tooltip" --key "ForegroundActive" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:View" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:View" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:View" --key "ForegroundActive" "$color0"

kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Window" --key "DecorationFocus" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Window" --key "DecorationHover" "$color0"
kwriteconfig5 --file ~/.config/kdeglobals --group "Colors:Window" --key "ForegroundActive" "$color0"




restart-kde