#!/bin/bash
bash install_favorites
bash install_binaries
bash install_realtek_alc3246
bash fixScreenTearing
bash handle_brightness_keys

sudo pacman --needed --noconfirm -S qtile
echo
echo "Configuring Qtile"
echo

cd ../.config/
echo "Removing previous qtile configuration"
rm -rv ~/.config/qtile
mkdir ~/.config/qtile
echo
echo "Moving new configuration"
cp -r qtile ~/.config/
cp -r dunst ~/.config/
cp -r picom ~/.config/
cp -r rofi ~/.config/
cp -r alacritty ~/.config/
cp -r nvim ~/.config/
cp -r smplayer ~/.config/
cp -r pulse ~/.config/

## Make qtile scripts executable
chmod +x ~/.config/qtile/scripts/*

echo
echo "Restarting qtile"
qtile-cmd -o cmd -f restart

echo
echo "Configuring Bash"
echo
cd ../Scripts/
bash install_bash

echo
printf "Do you want to install pulseaudio? [y/n]"
read choice

if [ $choice == y ]
then
    echo "Installing pulse"
    bash install_sound
    bash install_pulse_manjaro
fi


echo
printf "Do you want to install bluetooth? [y/n]"
read choice

if [ $choice == y ]
then
    echo "Installing bluetooth"
    bash install_bluetooth
fi

echo
echo "Configuration Complete"
