#!/bin/bash

### Upgrading the system
sudo pacman --noconfirm -Syyu

### Install aur helper
sudo pacman --needed --noconfirm -S yay

yay_install() {
    yay -S --noconfirm --needed $1
}

pacman_install() {
    sudo pacman -S --noconfirm --needed $1
}

pacmanlist=(
## notification daemon, rofi and alacritty
dunst 
rofi 
alacritty

## misc tools
flameshot 
fzf 
ripgrep


## Browsers
brave 
firefox 
qbittorrent

## File managers
thunar 
thunar-volman 
thunar-archive-plugin 
thunar-media-tags-plugin 
thunar-shares-plugin
gtkhash-thunar

## Media tools
audacious 
smplayer 
shotwell 
epdfview 
easytag 
playerctl

## Code Editors, Text Editors
neovim 
geany
marker

## Fonts
ttf-font-awesome 
ttf-jetbrains-mono 
ttf-inconsolata 
ttf-dejavu

## Wallpaper Changers
variety 
python-pywal 

## System utilities
arandr 
file-roller
polkit-gnome 
python-psutil
xfce4-power-manager 
xfce4-settings 
xfconf
qt5ct 
kvantum-qt5 
xcb-util-cursor

## Login manager
lightdm 
light-locker

)

yaylist=(
# Picom Compositor
picom-tryone-git

# Fonts
ttf-mononoki-git
)

count=0
for name in "${pacmanlist[@]}" ; do
	count=$[count+1]
	tput setaf 3;echo "Installing package nr.  "$count " " $name;tput sgr0;
	pacman_install $name
done

for name in "${yaylist[@]}" ; do
	count=$[count+1]
	tput setaf 3;echo "Installing package nr.  "$count " " $name;tput sgr0;
	yay_install $name
done


sudo systemctl enable lightdm.service -f
echo
echo
echo "Reboot to take effect"


