#!/bin/bash

packageListkde=(
flameshot
fzf
ripgrep
zsh

brave
firefox
qbittorrent

audacious
smplayer
playerctl

neovim

ttf-font-awesome
ttf-jetbrains-mono
ttf-inconsolata
ttf-dejavu

variety
python-pywal
krename
ffmpegthumbs
python3-pip
)

# echo $packageListkde
echo ${packageListkde[@]}