#!/bin/bash
echo
echo "Configuring Qtile"
echo

cd ../.config/
echo "Removing previous qtile configuration"
rm -rv ~/.config/qtile
mkdir ~/.config/qtile

echo "Moving new configuration"
cp -r qtile ~/.config/
cp -r dunst ~/.config/
cp -r picom ~/.config/
cp -r rofi ~/.config/
cp -r alacritty ~/.config/
cp -r nvim ~/.config/
cp -r smplayer ~/.config/
cp -r variety ~/.config/
cp -r pulse ~/.config/