#!/bin/bash

tput setaf 5;echo "Do you want to install Brave? [y/n]";tput sgr0;
read -t 30 -r input
case $input in
    y*) ;;
    *) exit ;;

esac

install_brave_dnf_nightly(){
    sudo dnf install dnf-plugins-core -y
    sudo dnf config-manager --add-repo https://brave-browser-rpm-nightly.s3.brave.com/x86_64/ -y
    sudo rpm --import https://brave-browser-rpm-nightly.s3.brave.com/brave-core-nightly.asc
    sudo dnf install brave-browser-nightly -y
}

install_brave_dnf_stable(){
    sudo dnf install dnf-plugins-core -y
    sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/ -y
    sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    sudo dnf install brave-browser  -y
}

install_brave_dnf_beta(){
    sudo dnf install dnf-plugins-core -y
    sudo dnf config-manager --add-repo https://brave-browser-rpm-beta.s3.brave.com/x86_64/ -y
    sudo rpm --import https://brave-browser-rpm-beta.s3.brave.com/brave-core-nightly.asc
    sudo dnf install brave-browser-beta -y
}



install_brave_apt_stable(){
    sudo apt install apt-transport-https curl gnupg -y
    curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add - -y
    echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
    sudo apt update -y
    sudo apt install brave-browser -y
}
install_brave_apt_beta(){
    sudo apt install apt-transport-https curl gnupg -y
    curl -s https://brave-browser-apt-beta.s3.brave.com/brave-core-nightly.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-prerelease.gpg add - -y
    echo "deb [arch=amd64] https://brave-browser-apt-beta.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-beta.list
    sudo apt update -y
    sudo apt install brave-browser-beta -y
}
install_brave_apt_nightly(){
    sudo apt install apt-transport-https curl gnupg -y
    curl -s https://brave-browser-apt-nightly.s3.brave.com/brave-core-nightly.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-prerelease.gpg add - -y
    echo "deb [arch=amd64] https://brave-browser-apt-nightly.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-nightly.list -y
    sudo apt update -y
    sudo apt install brave-browser-nightly -y
}

install_brave_pacman_stable(){
    yay -S --noconfirm --needed brave-bin
}
install_brave_pacman_beta(){
    yay -S --noconfirm --needed brave-beta-bin
}
install_brave_pacman_nightly(){
    yay -S --noconfirm --needed brave-nightly-bin
}

current_package_manager="$1"

tput setaf 1;echo "Which channel of Brave do you want to install?";tput sgr0;
tput setaf 4;echo "Stable: (1)";tput sgr0;
tput setaf 4;echo "Beta: (2)";tput sgr0;
tput setaf 4;echo "Nightly: (3)";tput sgr0;

read -t 30 -r channel

case $channel in
    1) echo "Installing Brave Stable"; "install_brave_""$current_package_manager""_stable";;
    2) echo "Installing Brave Beta"; "install_brave_""$current_package_manager""_beta";;
    3) echo "Installing Brave Nightly"; "install_brave_""$current_package_manager""_nightly";;
    *) echo "Installing Brave Stable"; "install_brave_""$current_package_manager""_stable";;
esac